name: Test Calculator

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

  jobs:
  unittests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: test sum_numbers function
        run: python -m unittest test_calculator.py
